image:
  - Visual Studio 2019
  - Ubuntu2004

version: "{build}"

shallow_clone: true

init:
  - git config --global core.autocrlf false

environment:
  matrix:
    # node.js
    - nodejs_version: stable

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install cypress
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - node run sapper
